### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by fennecbutt** [confuser/graphql-constraint-directive#15]
The example in the README doesn't work with the error: Error: Unknown directive "constraint".

As far as I can tell the directive returns its own definition, it shouldn't need to be defined in the graphql schema, right?

I've created a file containing only the js from the readme with the various imports installed, still get this error.

**Comment by fennecbutt** [comment]
I've just found that this is because of a breaking change in graphql 14 mentioned here: https://github.com/apollographql/graphql-tools/issues/957

Now we have to manually define custom directives in our schema...

**Comment by luismaldonadov** [comment]
I dont know if your problem is exactly like mine, but when working in custom directives for example

`extend type Query {
  me: String! @requireAuth
  user(userId: ID!): User! 
  users: [User]! 
}`

With the graphql-tools update , the definition of the directive is needed within the schema, something like this 

`directive @requireAuth on FIELD_DEFINITION`

Also i removed the direct dependency of graphql-tools because of the issue you referenced.

Hope this helps.

**Comment by anhldbk** [comment]
I've got the same problem

**Comment by BrenoMazieiro** [comment]
```js
const ConstraintDirective = require('graphql-constraint-directive')
const express = require('express')
const bodyParser = require('body-parser')
const { graphqlExpress } = require('apollo-server-express')
const { makeExecutableSchema } = require('graphql-tools')
const typeDefs = `
  directive @constraint on INPUT_FIELD_DEFINITION
  type Query {
    books: [Book]
  }
  type Book {
    title: String
  }
  type Mutation {
    createBook(input: BookInput): Book
  }
  input BookInput {
    title: String! @constraint(minLength: 5, format: "email")
  }`
const schema = makeExecutableSchema({
  typeDefs, schemaDirectives: { constraint: ConstraintDirective }
})
const app = express()

app.use('/graphql', bodyParser.json(), graphqlExpress({ schema }))

**Comment by rimiti** [comment]
Some problem.
