### ISSUE TITLE
Why does this directive throws a 400 Bad request?

### ISSUE THREAD

**Issue by ralphchristianeclipse** [confuser/graphql-constraint-directive#3]
Any way to format it instead to be the same with resolver errors?

**Comment by confuser** [comment]
This will be because the errors aren't thrown within a resolver function (although that may change, see #2). You can change the status code/error format within your error middleware, by checking for a [ConstraintDirectiveError](https://github.com/confuser/graphql-constraint-directive#constraintdirectiveerror)

**Comment by ralphchristianeclipse** [comment]
@confuser yes it would really help to put the error message directly on the message property

it treats it as a network error
